### ISSUE TITLE
Failed build when 2fa enabled

### ISSUE THREAD

**Issue by suzhaev** [bitrise-io/steps-deploy-to-itunesconnect-deliver#13]
I enabled 2FA for my iTunes Connect account. Are bitrise support it?

I tired deliver build to iTunes Connect, but it failed

```
[14:53:42]: Login to iTunes Connect (***@gmail.com)
Two Factor Authentication for account '***@gmail.com' is enabled
Please enter the 6 digit code: 
Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `[]=' for nil:NilClass for sigh manage
   https://github.com/fastlane/fastlane/issues/6751 [open] 3 💬
   a week ago

➡️  Pilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/3238 [open] 0 💬
   12 Sep 2016

➡️  Pilot Upload Failure undefined method `builds' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6381 [closed] 7 💬
   4 weeks ago

and 19 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60strip'%20for%20nil&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/question.rb:413:in `remove_whitespace': [!] undefined method `strip' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:873:in `get_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
	from /usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/two_step_client.rb:53:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/two_step_client.rb:40:in `handle_two_step'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:301:in `send_shared_login_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/tunes/tunes_client.rb:160:in `send_login_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:411:in `do_login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:230:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:90:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/runner.rb:14:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/runner.rb:7:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:47:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:128:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
 [!] Error description: Deploy failed!
     (i) Exit code was: 1
 (i) Calling cleanup function before exit
-> finalcleanup

# Error


**Error Description**:


Deploy failed!


*See the logs for more information*


**If this is the very first build**
of the app you try to deploy to iTunes Connect then you might want to upload the first
build manually to make sure it fulfills the initial iTunes Connect submission
verification process.

|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-deliver@2.6.2 (exit code: 1)          | 8.73 sec |
```

**Comment by viktorbenei** [comment]
AFAIK neither `deliver` nor Shenzhen support 2FA

You should report this on their GitHub page (https://github.com/fastlane/fastlane/tree/master/deliver), once it's supported by `deliver` it will work with this step too (as this step is built on top of `deliver`).

**Comment by viktorbenei** [comment]
Or, alternatively, use a "CI" iTunes Connect account where you don't enable 2FA. You'd use this account for nothing else, just for uploads.
